Name:           perl-Test-Tarantool
Version:        0.03
Release:        1%{?dist}
Summary:        Test::Tarantool Perl module
License:        OSI-Approved
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Test-Tarantool/
Source0:        http://www.cpan.org/authors/id/R/RE/REZNIKOV/Test-Tarantool-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
NAME       Test::Tarantool - The Swiss army knife for tests of Tarantool
related Perl and lua code.

%prep
%setup -q -n Test-Tarantool-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Jun 23 2017 Igor Munkin <imun@cpan.org> 0.03-1
- Specfile autogenerated by cpanspec 1.78.
